<form action="index.php?controller=status&task=save" method="POST" id="write-status">
    <div class="form-row">
        <input name="title" id="title" required placeholder="Entrez un titre"></input>
    </div>
    <div class="form-row">
        <input name="content" id="content" required placeholder="Rejoutez un commentaire"></input>
    </div>
    <div class="form-row">
        <input name="auteur" id="auteur" required placeholder="Nom de l'auteur"></input>
    </div>
    <select name="select">
        <option value="1">GDG</option>
        <option value="2">DFG</option>
        <option value="3">vOITUEE</option>
    </select>
    <button type="submit">
        <i class="fas fa-volume-up"></i>
        Envoyer
    </button>
</form>